### ISSUE TITLE
There are few css issues in the project.

### ISSUE THREAD

**Issue by jayboy-jp** [JayPokharkar/Hotel-Managemet-System#4]

**Comment by AmitPawar7** [comment]
Please assign this issue to me for my further contribution

**Comment by jayboy-jp** [comment]
@AmitPawar7  Issue has been assigned to you.

**Comment by Samruddhipatil7** [comment]
Assign the following issue to me...

**Comment by jayboy-jp** [comment]
Assigned to you as well.
